# Generated by Django 3.2.9 on 2021-12-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=12)),
                ('s0_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.spaceobjects')),
            ],
        ),
    ]
