# Generated by Django 3.2.9 on 2021-12-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_sopositions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=12)),
                ('time_s', models.DateTimeField()),
                ('so_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.spaceobjects')),
            ],
        ),
    ]
