# Generated by Django 3.2.9 on 2021-12-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_spaceobjects_exp_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='time_s',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='so_id',
        ),
        migrations.AddField(
            model_name='positions',
            name='short',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
