# Generated by Django 3.2.9 on 2021-12-08 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20211206_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='s_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 22, 2, 42, 891591)),
        ),
    ]
