# Generated by Django 3.2.9 on 2021-12-08 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20211208_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='s_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 23, 26, 3, 720589)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
