# Generated by Django 3.2.9 on 2021-12-12 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_alter_newsletter_s_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='s_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 16, 35, 11, 820054)),
        ),
    ]
